# Federated Instruction Tuning (static)
---
dataset:
  name: medalpaca/medical_meadow_medical_flashcards

# FL experimental settings
num_clients: 20 # total number of clients
num_rounds: 200
partitioner:
  _target_: flwr_datasets.partitioner.IidPartitioner
  num_partitions: 20
